require 'fileutils'
require 'pathname'
require 'json'
require 'nokogiri'
require 'open-uri'
require 'digest'
require 'byebug'


require 'catalog'
require 'builder'
require 'scrapers/base'
require 'scrapers/wiki_list'
require 'scrapers/ki54'
require 'scrapers/ku7'
