require 'fileutils'
require 'pathname'
require 'json'
require 'nokogiri'
require 'open-uri'
require 'digest'
require 'byebug'


require 'catalog'
require 'builder'
require 'scrapers/base'
require 'scrapers/wiki_list'
require 'scrapers/e2n'
require 'scrapers/e10a'
require 'scrapers/e11a'
require 'scrapers/g5n'
require 'scrapers/h3k'
require 'scrapers/h5y'
require 'scrapers/k10w'
require 'scrapers/ki2'
require 'scrapers/ki17'
require 'scrapers/ki54'
require 'scrapers/ki55'
require 'scrapers/ki70'
require 'scrapers/ku7'
require 'scrapers/ku8'
require 'scrapers/q1w'
